name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          # This command answers 'y' to everything and runs the build
          yes y | /home/runner/.local/bin/buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PoolHelper-APK
          path: bin/*.apk
